apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: postgresql
  namespace: patchlab
  resourceVersion: '9170126'
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: '172.30.1.1:5000/openshift/postgresql:10'
      generation: 2
      importPolicy: {}
      name: '10'
      referencePolicy:
        type: Source
