apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: patchlab
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        openshift.io/imported-from: rabbitmq
      from:
        kind: DockerImage
        name: rabbitmq
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
