apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: patchlab
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: rabbitmq
    deploymentconfig: rabbitmq
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: rabbitmq
        deploymentconfig: rabbitmq
    spec:
      containers:
        - image: >-
            rabbitmq@sha256:ea597cc3ffaa098a550a2dc02483ea4b399c93a1394f968af78ee8bfc5fd21a1
          imagePullPolicy: Always
          name: rabbitmq
          ports:
            - containerPort: 4369
              protocol: TCP
            - containerPort: 5671
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
            - containerPort: 25672
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: rabbitmq-volume-1
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - rabbitmq
        from:
          kind: ImageStreamTag
          name: 'rabbitmq:latest'
          namespace: patchlab
        lastTriggeredImage: >-
          rabbitmq@sha256:ea597cc3ffaa098a550a2dc02483ea4b399c93a1394f968af78ee8bfc5fd21a1
      type: ImageChange
