apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2020-05-04T13:00:46Z'
  labels:
    app: postgresql
  name: postgresql
  namespace: patchlab
  resourceVersion: '9170123'
  selfLink: /api/v1/namespaces/patchlab/services/postgresql
  uid: 456b1fb8-8e07-11ea-9260-525400a8c108
spec:
  clusterIP: 172.30.102.177
  ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgresql
    deploymentconfig: postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
