apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: '2020-05-04T13:02:51Z'
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: patchlab
  resourceVersion: '9170751'
  selfLink: /api/v1/namespaces/patchlab/services/rabbitmq
  uid: 8fb1fe4a-8e07-11ea-9260-525400a8c108
spec:
  clusterIP: 172.30.182.230
  ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5671-tcp
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 25672-tcp
      port: 25672
      protocol: TCP
      targetPort: 25672
  selector:
    app: rabbitmq
    deploymentconfig: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
